#!/usr/bin/with-contenv sh
set -e
function check_exit_code {
	EXIT_CODE=$?
	if [[ $EXIT_CODE -ne 0 ]]; then
		echo $EXIT_CODE >/run/s6-linux-init-container-results/exitcode
		/run/s6/basedir/bin/halt
	fi
}
trap check_exit_code EXIT
while [[ ! -S /run/cloudflare-warp/warp_service ]]; do sleep 0.1; done
while [[ ! -f /var/lib/cloudflare-warp/reg.json ]]; do
	/usr/local/bin/warp-cli --accept-tos register || sleep 5
done

if [ ! -z "$WARP_PLUS_LICENCE" ]; then
	/usr/local/bin/warp-cli --accept-tos set-license $WARP_PLUS_LICENCE
fi

/usr/local/bin/warp-cli --accept-tos set-mode proxy
/usr/local/bin/warp-cli --accept-tos connect
/usr/local/bin/warp-cli --accept-tos enable-always-on
while [[ ! -d /sys/class/net/CloudflareWARP ]]; do sleep 0.1; done
